#!/usr/bin/ruby

module DICE
  TARGET = 's1628873@ssh.inf.ed.ac.uk'
  SSH = "ssh -t #{TARGET}"

  class << self
    def start argv
      if argv.empty?
        exec SSH + ' ssh student.login'
      elsif argv.size == 1
        if %w[--compute -c].include? argv.first
          exec SSH + ' ssh ashbury'
        elsif %w[--cluster -C].include? argv.first
          exec SSH + ' ssh hadoop.exc'
        elsif %w[--gpu -g].include? argv.first
          exec SSH + ' ssh atlas'
        elsif %w[--path -p].include? argv.first
          puts TARGET
        else
          help
        end
      elsif argv.size == 2
        if %w[--path -p].include? argv.first
          puts TARGET + ':' + argv[1]
        else
          help
        end
      else
        help
      end
    end

    private

    def help
      puts
      puts 'Commands:'
      puts '  dice                   # SSH into DICE'
      puts '  dice --compute, -c     # SSH into student.compute (ashbury)'
      puts '  dice --cluster, -C     # SSH into hadoop.exc (scutter)'
      puts '  dice --gpu, -g         # SSH into GPU (atlas)'
      puts '  dice --path, -p PATH   # Path on DICE account, with SSH target'
    end
  end
end

DICE.start ARGV
