#!/usr/bin/env ruby

module DICE
  TARGET = 's1628873@ssh.inf.ed.ac.uk'
  SSH = "ssh -t #{TARGET}"

  class << self
    def start argv
      if argv.empty?
        exec "#{SSH} ssh student.login"
      elsif argv.size == 1
        if %w[--compute -c].include? argv.first
          exec "#{SSH} ssh ashbury"
        elsif %w[--gpu -g].include? argv.first
          exec "#{SSH} ssh waititi"
        elsif %w[--path -p].include? argv.first
          puts TARGET
        else
          help
        end
      elsif argv.size == 2
        if %w[--path -p].include? argv.first
          puts "#{TARGET}:#{argv[1]}"
        elsif %w[--machine -m].include? argv.first
          exec "#{SSH} ssh #{argv[1]}"
        else
          help
        end
      else
        help
      end
    end

    private

    def help
      puts
      puts "\e[4mdice\e[0m: Shortcut commands for connecting to DICE"
      puts
      puts "\e[1mCommands\e[0m:"
      puts "  dice                           \e[37m#\e[0m \e[90mSSH into DICE\e[0m"
      puts "  dice --compute, -c             \e[37m#\e[0m \e[90mSSH into student.compute (ashbury)\e[0m"
      puts "  dice --gpu, -g                 \e[37m#\e[0m \e[90mSSH into GPU (waititi)\e[0m"
      puts "  dice --machine, -m [MACHINE]   \e[37m#\e[0m \e[90mSSH into a specific DICE machine\e[0m"
      puts "  dice --path, -p [PATH]         \e[37m#\e[0m \e[90mPath on DICE account, with SSH target\e[0m"
    end
  end
end

DICE.start ARGV