#!/usr/bin/env ruby

require 'fileutils'

class Note
  DIRECTORY = '/Users/edwinonuonga/dropbox/university/year4/sem1'
  LATEX = '/Users/edwinonuonga/development/latex/mytex/mytex.tex'

  @args = []

  def initialize
    @args = ARGV

    if help?
      puts "  USAGE: make-note <course-abbr> <file-name> <description>"
    else
      @course = @args.first
      @file = File.join @course, 'notes', (@args[1].end_with?('.md') ? @args[1] : "#{@args[1]}.md")
      @desc = @args.last

      create
    end
  end

  private

  def create
    Dir.chdir DIRECTORY do
      # Prompt to create course folder (if it doesn't already exist)
      unless course? @course
        make = prompt "Course notes folder '#@course/notes' doesn't exist. Create anyway? (Y/n): "
        if %w[Y y Yes yes YES].include? make
          FileUtils.mkdir_p File.join(@course, 'notes')
        else
          return
        end
      end

      # Raise error if note file already exists
      raise Errno::EEXIST.new(File.join(DIRECTORY, @file)) if File.file? @file

      # Create note file
      File.open(@file, 'w') do |f|
        f << <<~HEREDOC
          $$
          #{File.read LATEX}
          $$

          # #{@course.upcase}

          *#@desc*

          ---



          ---
        HEREDOC
      end

      # Open note file in Typora
      # exec "typora #@file"
    end
  end

  def help?
    @args.empty? || @args.include?('-h')
  end

  def course? directory
    Dir.chdir(DIRECTORY) { File.directory? File.join(directory, 'notes') }
  end

  def prompt message
    print message
    STDIN.gets.chomp
  end
end

Note.new