#!/usr/bin/env ruby

class NBStart
  def start(args)
    if args.empty?
      run 9292
    elsif args.size == 1
      arg = args.first
      help if arg == '-h'
      raise TypeError.new('Expected port to be an integer') unless /\A[-+]?\d+\z/ =~ arg
      raise ArgumentError.new('Expected port to be between 0-65535') unless (0..65535).include? arg.to_i
      run arg
    else
      help
    end
  end

  def run(args)
    exec "screen -S notebook nice -n 19 jupyter notebook --no-browser --port=#{args}"
  end

  def help
    puts
    puts "\e[4mnbstart\e[0m: Start a Jupyter notebook to run over SSH"
    puts
    puts "\e[1mUsage\e[0m:"
    puts "  nbstart [PORT]      \e[90m# Defaults to 9292\e[0m"
    puts
    exit 0
  end
end

nbstart = NBStart.new
nbstart.start ARGV